services:
  db:
    image: postgres:18
    container_name: matcha-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:132456789}
      POSTGRES_DB: matcha_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d matcha_db -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  pgdata:
